### ISSUE TITLE
the Vertices value?

### ISSUE THREAD

**Issue by moseshu** [soundcloud/spark-pagerank#43]
Hello!
I have question about the result of the Vertice. the code is in the PageRank.scala file,
for example :

val actual = PageRank.run(
graph, teleportProb,
maxIterations,
convergenceThreshold
).collect()

Does the larger value indicates a stronger importance ?
if I use this value in black list,it indicates that 
the person is more dangerous?Is it right?

**Comment by joshdevins** [comment]
The higher the vertex value, the more influence they have in the graph. The values are the probability that a random visitor will land on that node. You shouldn't use it to indicate a "bad" or "good" user.
